spring.application.name=platform-service
server.port=${SERVER_PORT:8761}
spring.profiles.active=native
spring.cloud.config.server.native.search-locations=${CONFIG_REPO_LOCATION:file:../config-repo/}
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false
eureka.client.service-url.defaultZone=http://localhost:${server.port}/eureka/
management.endpoints.web.exposure.include=health
server.shutdown=graceful
